import { SessionProvider } from 'next-auth/react';
import { AppProps } from 'next/app';
import "@/styles/globals.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ModalProvider } from '@/context/ModalContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function App({ Component, pageProps }: AppProps) {
    
  return (

		<SessionProvider session={pageProps.session}>
			<div className={inter.className}>
				<ModalProvider>
					
						<Component {...pageProps} />
					
				</ModalProvider>
			</div>
		</SessionProvider>
  );
}

export default App;
